name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # data branch syncing removed per user request

      - uses: actions/setup-node@v3
        if: github.ref == 'refs/heads/main'
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        if: github.ref == 'refs/heads/main'
        run: npm ci

      - name: Build
        if: github.ref == 'refs/heads/main'
        run: npm run build --if-present
        env:
          GITHUB_PAGES: 'true'

      - name: Show built files
        if: github.ref == 'refs/heads/main'
        run: ls -la ./dist || true

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
