name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
      - data
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Sync project data from data branch
        run: |
          if git ls-remote --exit-code origin data >/dev/null 2>&1; then
            echo "data branch detected. Syncing projects.ts"
            git fetch origin data --depth=1
            git show origin/data:src/data/projects.ts > src/data/projects.ts
          else
            echo "data branch not found. Skipping data sync."
          fi
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build --if-present
        env:
          GITHUB_PAGES: 'true'

      - name: Show built files
        run: ls -la ./dist || true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
