name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
      - data
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout main branch snapshot
        if: github.ref == 'refs/heads/data'
        uses: actions/checkout@v4
        with:
          ref: main
          path: main-branch
          fetch-depth: 0

      - name: Sync projects.ts from data into main
        if: github.ref == 'refs/heads/data'
        run: |
          cp src/data/projects.ts main-branch/src/data/projects.ts
          cd main-branch
          git add src/data/projects.ts
          if git diff --cached --quiet; then
            echo "No changes to sync into main."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "Sync projects data from data branch"
            git push origin HEAD:main
          fi

      - uses: actions/setup-node@v3
        if: github.ref == 'refs/heads/main'
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        if: github.ref == 'refs/heads/main'
        run: npm ci

      - name: Build
        if: github.ref == 'refs/heads/main'
        run: npm run build --if-present
        env:
          GITHUB_PAGES: 'true'

      - name: Show built files
        if: github.ref == 'refs/heads/main'
        run: ls -la ./dist || true

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
