name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
      - data
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Checkout data branch
        uses: actions/checkout@v4
        with:
          ref: data
          path: data-branch
          fetch-depth: 1

      - name: Sync project data from data branch
        run: |
          if [ ! -f "data-branch/src/data/projects.ts" ]; then
            echo "projects.ts not found in data branch."
            exit 1
          fi
          cp data-branch/src/data/projects.ts src/data/projects.ts
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build --if-present
        env:
          GITHUB_PAGES: 'true'

      - name: Show built files
        run: ls -la ./dist || true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
